export const fakeHistory2 = {
    location: {
        name: 'Ho Chi Minh City',
        region: '',
        country: 'Vietnam',
        lat: 10.75,
        lon: 106.67,
        tz_id: 'Asia/Ho_Chi_Minh',
        localtime_epoch: 1702981721,
        localtime: '2023-12-19 17:28',
    },
    forecast: {
        forecastday: [
            {
                date: '2023-12-17',
                date_epoch: 1702771200,
                day: {
                    maxtemp_c: 33.6,
                    maxtemp_f: 92.4,
                    mintemp_c: 24.2,
                    mintemp_f: 75.6,
                    avgtemp_c: 27.9,
                    avgtemp_f: 82.3,
                    maxwind_mph: 7.8,
                    maxwind_kph: 12.6,
                    totalprecip_mm: 0.37,
                    totalprecip_in: 0.01,
                    totalsnow_cm: 0.0,
                    avgvis_km: 10.0,
                    avgvis_miles: 6.0,
                    avghumidity: 68.0,
                    daily_will_it_rain: 1,
                    daily_chance_of_rain: 100,
                    daily_will_it_snow: 0,
                    daily_chance_of_snow: 0,
                    condition: {
                        text: 'Patchy rain possible',
                        icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                        code: 1063,
                    },
                    uv: 7.0,
                },
                astro: {
                    sunrise: '06:04 AM',
                    sunset: '05:34 PM',
                    moonrise: '10:02 AM',
                    moonset: '09:59 PM',
                    moon_phase: 'Waxing Crescent',
                    moon_illumination: 20,
                },
                hour: [
                    {
                        time_epoch: 1702746000,
                        time: '2023-12-17 00:00',
                        temp_c: 25.4,
                        temp_f: 77.7,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.1,
                        wind_kph: 8.3,
                        wind_degree: 144,
                        wind_dir: 'SE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.86,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 81,
                        cloud: 21,
                        feelslike_c: 27.7,
                        feelslike_f: 81.8,
                        windchill_c: 25.4,
                        windchill_f: 77.7,
                        heatindex_c: 27.7,
                        heatindex_f: 81.8,
                        dewpoint_c: 21.9,
                        dewpoint_f: 71.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.5,
                        gust_kph: 13.6,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702749600,
                        time: '2023-12-17 01:00',
                        temp_c: 25.0,
                        temp_f: 77.0,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 4.0,
                        wind_kph: 6.5,
                        wind_degree: 119,
                        wind_dir: 'ESE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.85,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 83,
                        cloud: 22,
                        feelslike_c: 27.3,
                        feelslike_f: 81.1,
                        windchill_c: 25.0,
                        windchill_f: 77.0,
                        heatindex_c: 27.3,
                        heatindex_f: 81.1,
                        dewpoint_c: 21.9,
                        dewpoint_f: 71.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.7,
                        gust_kph: 10.8,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702753200,
                        time: '2023-12-17 02:00',
                        temp_c: 24.7,
                        temp_f: 76.5,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 4.0,
                        wind_kph: 6.5,
                        wind_degree: 74,
                        wind_dir: 'ENE',
                        pressure_mb: 1010.0,
                        pressure_in: 29.84,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 83,
                        cloud: 21,
                        feelslike_c: 26.9,
                        feelslike_f: 80.4,
                        windchill_c: 24.7,
                        windchill_f: 76.5,
                        heatindex_c: 26.9,
                        heatindex_f: 80.4,
                        dewpoint_c: 21.6,
                        dewpoint_f: 70.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.8,
                        gust_kph: 10.9,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702756800,
                        time: '2023-12-17 03:00',
                        temp_c: 24.6,
                        temp_f: 76.3,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 4.7,
                        wind_kph: 7.6,
                        wind_degree: 42,
                        wind_dir: 'NE',
                        pressure_mb: 1010.0,
                        pressure_in: 29.84,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 81,
                        cloud: 20,
                        feelslike_c: 26.7,
                        feelslike_f: 80.0,
                        windchill_c: 24.6,
                        windchill_f: 76.3,
                        heatindex_c: 26.7,
                        heatindex_f: 80.0,
                        dewpoint_c: 21.2,
                        dewpoint_f: 70.1,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.1,
                        gust_kph: 13.1,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702760400,
                        time: '2023-12-17 04:00',
                        temp_c: 24.6,
                        temp_f: 76.2,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.4,
                        wind_kph: 8.6,
                        wind_degree: 23,
                        wind_dir: 'NNE',
                        pressure_mb: 1010.0,
                        pressure_in: 29.84,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 80,
                        cloud: 17,
                        feelslike_c: 26.5,
                        feelslike_f: 79.8,
                        windchill_c: 24.6,
                        windchill_f: 76.2,
                        heatindex_c: 26.5,
                        heatindex_f: 79.8,
                        dewpoint_c: 20.9,
                        dewpoint_f: 69.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.5,
                        gust_kph: 15.3,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702764000,
                        time: '2023-12-17 05:00',
                        temp_c: 24.4,
                        temp_f: 76.0,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.4,
                        wind_kph: 8.6,
                        wind_degree: 15,
                        wind_dir: 'NNE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.85,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 80,
                        cloud: 15,
                        feelslike_c: 26.4,
                        feelslike_f: 79.5,
                        windchill_c: 24.4,
                        windchill_f: 76.0,
                        heatindex_c: 26.4,
                        heatindex_f: 79.5,
                        dewpoint_c: 20.8,
                        dewpoint_f: 69.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.5,
                        gust_kph: 15.3,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702767600,
                        time: '2023-12-17 06:00',
                        temp_c: 24.2,
                        temp_f: 75.6,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.1,
                        wind_kph: 8.3,
                        wind_degree: 22,
                        wind_dir: 'NNE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.87,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 81,
                        cloud: 17,
                        feelslike_c: 26.2,
                        feelslike_f: 79.2,
                        windchill_c: 24.2,
                        windchill_f: 75.6,
                        heatindex_c: 26.2,
                        heatindex_f: 79.2,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.1,
                        gust_kph: 14.7,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702771200,
                        time: '2023-12-17 07:00',
                        temp_c: 25.1,
                        temp_f: 77.2,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.1,
                        wind_kph: 8.3,
                        wind_degree: 19,
                        wind_dir: 'NNE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.89,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 78,
                        cloud: 16,
                        feelslike_c: 27.1,
                        feelslike_f: 80.8,
                        windchill_c: 25.1,
                        windchill_f: 77.2,
                        heatindex_c: 27.1,
                        heatindex_f: 80.8,
                        dewpoint_c: 21.0,
                        dewpoint_f: 69.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.9,
                        gust_kph: 12.7,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702774800,
                        time: '2023-12-17 08:00',
                        temp_c: 27.2,
                        temp_f: 80.9,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 6.0,
                        wind_kph: 9.7,
                        wind_degree: 16,
                        wind_dir: 'NNE',
                        pressure_mb: 1013.0,
                        pressure_in: 29.92,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 68,
                        cloud: 15,
                        feelslike_c: 29.3,
                        feelslike_f: 84.8,
                        windchill_c: 27.2,
                        windchill_f: 80.9,
                        heatindex_c: 29.3,
                        heatindex_f: 84.8,
                        dewpoint_c: 20.8,
                        dewpoint_f: 69.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.4,
                        gust_kph: 11.9,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702778400,
                        time: '2023-12-17 09:00',
                        temp_c: 29.1,
                        temp_f: 84.4,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9.0,
                        wind_degree: 15,
                        wind_dir: 'NNE',
                        pressure_mb: 1013.0,
                        pressure_in: 29.92,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 60,
                        cloud: 14,
                        feelslike_c: 31.6,
                        feelslike_f: 88.8,
                        windchill_c: 29.1,
                        windchill_f: 84.4,
                        heatindex_c: 31.6,
                        heatindex_f: 88.8,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.4,
                        gust_kph: 10.4,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702782000,
                        time: '2023-12-17 10:00',
                        temp_c: 30.8,
                        temp_f: 87.4,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 4.7,
                        wind_kph: 7.6,
                        wind_degree: 19,
                        wind_dir: 'NNE',
                        pressure_mb: 1013.0,
                        pressure_in: 29.9,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 55,
                        cloud: 15,
                        feelslike_c: 33.6,
                        feelslike_f: 92.5,
                        windchill_c: 30.8,
                        windchill_f: 87.4,
                        heatindex_c: 33.6,
                        heatindex_f: 92.5,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 5.4,
                        gust_kph: 8.7,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702785600,
                        time: '2023-12-17 11:00',
                        temp_c: 32.3,
                        temp_f: 90.2,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 2.9,
                        wind_kph: 4.7,
                        wind_degree: 19,
                        wind_dir: 'NNE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.88,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 51,
                        cloud: 16,
                        feelslike_c: 35.7,
                        feelslike_f: 96.2,
                        windchill_c: 32.3,
                        windchill_f: 90.2,
                        heatindex_c: 35.7,
                        heatindex_f: 96.2,
                        dewpoint_c: 20.8,
                        dewpoint_f: 69.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 3.4,
                        gust_kph: 5.4,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702789200,
                        time: '2023-12-17 12:00',
                        temp_c: 33.3,
                        temp_f: 91.9,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 2.2,
                        wind_kph: 3.6,
                        wind_degree: 33,
                        wind_dir: 'NNE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.84,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 48,
                        cloud: 19,
                        feelslike_c: 36.8,
                        feelslike_f: 98.3,
                        windchill_c: 33.3,
                        windchill_f: 91.9,
                        heatindex_c: 36.8,
                        heatindex_f: 98.3,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 2.6,
                        gust_kph: 4.1,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702792800,
                        time: '2023-12-17 13:00',
                        temp_c: 33.6,
                        temp_f: 92.4,
                        is_day: 1,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                            code: 1003,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4.0,
                        wind_degree: 56,
                        wind_dir: 'ENE',
                        pressure_mb: 1009.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 46,
                        cloud: 44,
                        feelslike_c: 37.0,
                        feelslike_f: 98.5,
                        windchill_c: 33.6,
                        windchill_f: 92.4,
                        heatindex_c: 37.0,
                        heatindex_f: 98.5,
                        dewpoint_c: 20.4,
                        dewpoint_f: 68.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 2.8,
                        gust_kph: 4.6,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702796400,
                        time: '2023-12-17 14:00',
                        temp_c: 33.3,
                        temp_f: 92.0,
                        is_day: 1,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                            code: 1063,
                        },
                        wind_mph: 1.3,
                        wind_kph: 2.2,
                        wind_degree: 61,
                        wind_dir: 'ENE',
                        pressure_mb: 1008.0,
                        pressure_in: 29.77,
                        precip_mm: 0.07,
                        precip_in: 0.0,
                        humidity: 46,
                        cloud: 80,
                        feelslike_c: 36.5,
                        feelslike_f: 97.6,
                        windchill_c: 33.3,
                        windchill_f: 92.0,
                        heatindex_c: 36.5,
                        heatindex_f: 97.6,
                        dewpoint_c: 20.1,
                        dewpoint_f: 68.3,
                        will_it_rain: 0,
                        chance_of_rain: 45,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 1.5,
                        gust_kph: 2.5,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702800000,
                        time: '2023-12-17 15:00',
                        temp_c: 32.8,
                        temp_f: 91.1,
                        is_day: 1,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                            code: 1003,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4.0,
                        wind_degree: 199,
                        wind_dir: 'SSW',
                        pressure_mb: 1008.0,
                        pressure_in: 29.75,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 48,
                        cloud: 59,
                        feelslike_c: 36.1,
                        feelslike_f: 96.9,
                        windchill_c: 32.9,
                        windchill_f: 91.1,
                        heatindex_c: 36.1,
                        heatindex_f: 96.9,
                        dewpoint_c: 20.5,
                        dewpoint_f: 68.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 3.1,
                        gust_kph: 5.0,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702803600,
                        time: '2023-12-17 16:00',
                        temp_c: 31.8,
                        temp_f: 89.3,
                        is_day: 1,
                        condition: {
                            text: 'Cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                            code: 1006,
                        },
                        wind_mph: 6.3,
                        wind_kph: 10.1,
                        wind_degree: 176,
                        wind_dir: 'S',
                        pressure_mb: 1008.0,
                        pressure_in: 29.76,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 53,
                        cloud: 71,
                        feelslike_c: 35.2,
                        feelslike_f: 95.4,
                        windchill_c: 31.8,
                        windchill_f: 89.3,
                        heatindex_c: 35.2,
                        heatindex_f: 95.4,
                        dewpoint_c: 21.1,
                        dewpoint_f: 70.0,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.4,
                        gust_kph: 13.5,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702807200,
                        time: '2023-12-17 17:00',
                        temp_c: 29.8,
                        temp_f: 85.6,
                        is_day: 1,
                        condition: {
                            text: 'Cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                            code: 1006,
                        },
                        wind_mph: 7.8,
                        wind_kph: 12.6,
                        wind_degree: 162,
                        wind_dir: 'SSE',
                        pressure_mb: 1009.0,
                        pressure_in: 29.79,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 62,
                        cloud: 70,
                        feelslike_c: 33.0,
                        feelslike_f: 91.4,
                        windchill_c: 29.8,
                        windchill_f: 85.6,
                        heatindex_c: 33.0,
                        heatindex_f: 91.4,
                        dewpoint_c: 21.7,
                        dewpoint_f: 71.1,
                        will_it_rain: 0,
                        chance_of_rain: 45,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 11.9,
                        gust_kph: 19.1,
                        uv: 6.0,
                    },
                    {
                        time_epoch: 1702810800,
                        time: '2023-12-17 18:00',
                        temp_c: 28.5,
                        temp_f: 83.3,
                        is_day: 0,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                            code: 1063,
                        },
                        wind_mph: 7.2,
                        wind_kph: 11.5,
                        wind_degree: 159,
                        wind_dir: 'SSE',
                        pressure_mb: 1010.0,
                        pressure_in: 29.81,
                        precip_mm: 0.11,
                        precip_in: 0.0,
                        humidity: 66,
                        cloud: 72,
                        feelslike_c: 31.3,
                        feelslike_f: 88.3,
                        windchill_c: 28.5,
                        windchill_f: 83.4,
                        heatindex_c: 31.3,
                        heatindex_f: 88.3,
                        dewpoint_c: 21.5,
                        dewpoint_f: 70.6,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 11.5,
                        gust_kph: 18.6,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702814400,
                        time: '2023-12-17 19:00',
                        temp_c: 27.1,
                        temp_f: 80.7,
                        is_day: 0,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                            code: 1063,
                        },
                        wind_mph: 6.5,
                        wind_kph: 10.4,
                        wind_degree: 157,
                        wind_dir: 'SSE',
                        pressure_mb: 1010.0,
                        pressure_in: 29.84,
                        precip_mm: 0.14,
                        precip_in: 0.01,
                        humidity: 73,
                        cloud: 82,
                        feelslike_c: 29.6,
                        feelslike_f: 85.3,
                        windchill_c: 27.1,
                        windchill_f: 80.7,
                        heatindex_c: 29.6,
                        heatindex_f: 85.3,
                        dewpoint_c: 21.8,
                        dewpoint_f: 71.2,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 11.2,
                        gust_kph: 18.0,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702818000,
                        time: '2023-12-17 20:00',
                        temp_c: 26.2,
                        temp_f: 79.1,
                        is_day: 0,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                            code: 1063,
                        },
                        wind_mph: 6.0,
                        wind_kph: 9.7,
                        wind_degree: 150,
                        wind_dir: 'SSE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.86,
                        precip_mm: 0.06,
                        precip_in: 0.0,
                        humidity: 77,
                        cloud: 76,
                        feelslike_c: 28.5,
                        feelslike_f: 83.4,
                        windchill_c: 26.2,
                        windchill_f: 79.1,
                        heatindex_c: 28.5,
                        heatindex_f: 83.4,
                        dewpoint_c: 21.8,
                        dewpoint_f: 71.3,
                        will_it_rain: 0,
                        chance_of_rain: 45,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 10.7,
                        gust_kph: 17.2,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702821600,
                        time: '2023-12-17 21:00',
                        temp_c: 25.8,
                        temp_f: 78.4,
                        is_day: 0,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                            code: 1003,
                        },
                        wind_mph: 4.3,
                        wind_kph: 6.8,
                        wind_degree: 135,
                        wind_dir: 'SE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.87,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 79,
                        cloud: 31,
                        feelslike_c: 28.1,
                        feelslike_f: 82.6,
                        windchill_c: 25.8,
                        windchill_f: 78.4,
                        heatindex_c: 28.1,
                        heatindex_f: 82.6,
                        dewpoint_c: 21.8,
                        dewpoint_f: 71.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.6,
                        gust_kph: 12.2,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702825200,
                        time: '2023-12-17 22:00',
                        temp_c: 25.7,
                        temp_f: 78.3,
                        is_day: 0,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                            code: 1003,
                        },
                        wind_mph: 2.9,
                        wind_kph: 4.7,
                        wind_degree: 125,
                        wind_dir: 'SE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.87,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 79,
                        cloud: 28,
                        feelslike_c: 28.0,
                        feelslike_f: 82.3,
                        windchill_c: 25.7,
                        windchill_f: 78.3,
                        heatindex_c: 28.0,
                        heatindex_f: 82.3,
                        dewpoint_c: 21.7,
                        dewpoint_f: 71.0,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 5.2,
                        gust_kph: 8.3,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702828800,
                        time: '2023-12-17 23:00',
                        temp_c: 25.5,
                        temp_f: 77.9,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4.0,
                        wind_degree: 81,
                        wind_dir: 'E',
                        pressure_mb: 1011.0,
                        pressure_in: 29.86,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 79,
                        cloud: 20,
                        feelslike_c: 27.7,
                        feelslike_f: 81.9,
                        windchill_c: 25.5,
                        windchill_f: 77.9,
                        heatindex_c: 27.7,
                        heatindex_f: 81.9,
                        dewpoint_c: 21.6,
                        dewpoint_f: 70.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 4.4,
                        gust_kph: 7.0,
                        uv: 1.0,
                    },
                ],
            },
        ],
    },
}
