export const fakeHistory1 = {
    location: {
        name: 'Ho Chi Minh City',
        region: '',
        country: 'Vietnam',
        lat: 10.75,
        lon: 106.67,
        tz_id: 'Asia/Ho_Chi_Minh',
        localtime_epoch: 1702981669,
        localtime: '2023-12-19 17:27',
    },
    forecast: {
        forecastday: [
            {
                date: '2023-12-18',
                date_epoch: 1702857600,
                day: {
                    maxtemp_c: 34.5,
                    maxtemp_f: 94.1,
                    mintemp_c: 23.2,
                    mintemp_f: 73.7,
                    avgtemp_c: 28.0,
                    avgtemp_f: 82.3,
                    maxwind_mph: 7.6,
                    maxwind_kph: 12.2,
                    totalprecip_mm: 0.21,
                    totalprecip_in: 0.01,
                    totalsnow_cm: 0.0,
                    avgvis_km: 10.0,
                    avgvis_miles: 6.0,
                    avghumidity: 66.0,
                    daily_will_it_rain: 1,
                    daily_chance_of_rain: 100,
                    daily_will_it_snow: 0,
                    daily_chance_of_snow: 0,
                    condition: {
                        text: 'Patchy rain possible',
                        icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                        code: 1063,
                    },
                    uv: 7.0,
                },
                astro: {
                    sunrise: '06:05 AM',
                    sunset: '05:35 PM',
                    moonrise: '10:50 AM',
                    moonset: '10:55 PM',
                    moon_phase: 'Waxing Crescent',
                    moon_illumination: 30,
                },
                hour: [
                    {
                        time_epoch: 1702832400,
                        time: '2023-12-18 00:00',
                        temp_c: 25.5,
                        temp_f: 77.8,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.6,
                        wind_kph: 5.8,
                        wind_degree: 351,
                        wind_dir: 'N',
                        pressure_mb: 1011.0,
                        pressure_in: 29.86,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 79,
                        cloud: 19,
                        feelslike_c: 27.7,
                        feelslike_f: 81.8,
                        windchill_c: 25.5,
                        windchill_f: 77.8,
                        heatindex_c: 27.7,
                        heatindex_f: 81.8,
                        dewpoint_c: 21.6,
                        dewpoint_f: 70.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.3,
                        gust_kph: 10.2,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702836000,
                        time: '2023-12-18 01:00',
                        temp_c: 25.1,
                        temp_f: 77.1,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 4.0,
                        wind_kph: 6.5,
                        wind_degree: 359,
                        wind_dir: 'N',
                        pressure_mb: 1011.0,
                        pressure_in: 29.85,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 81,
                        cloud: 21,
                        feelslike_c: 27.2,
                        feelslike_f: 81.0,
                        windchill_c: 25.1,
                        windchill_f: 77.1,
                        heatindex_c: 27.2,
                        heatindex_f: 81.0,
                        dewpoint_c: 21.5,
                        dewpoint_f: 70.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.1,
                        gust_kph: 11.4,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702839600,
                        time: '2023-12-18 02:00',
                        temp_c: 24.6,
                        temp_f: 76.3,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.8,
                        wind_kph: 6.1,
                        wind_degree: 359,
                        wind_dir: 'N',
                        pressure_mb: 1011.0,
                        pressure_in: 29.84,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 82,
                        cloud: 14,
                        feelslike_c: 26.7,
                        feelslike_f: 80.1,
                        windchill_c: 24.6,
                        windchill_f: 76.3,
                        heatindex_c: 26.7,
                        heatindex_f: 80.1,
                        dewpoint_c: 21.3,
                        dewpoint_f: 70.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.6,
                        gust_kph: 10.7,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702843200,
                        time: '2023-12-18 03:00',
                        temp_c: 24.2,
                        temp_f: 75.6,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 4.0,
                        wind_kph: 6.5,
                        wind_degree: 343,
                        wind_dir: 'NNW',
                        pressure_mb: 1010.0,
                        pressure_in: 29.83,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 82,
                        cloud: 9,
                        feelslike_c: 26.3,
                        feelslike_f: 79.3,
                        windchill_c: 24.2,
                        windchill_f: 75.6,
                        heatindex_c: 26.3,
                        heatindex_f: 79.3,
                        dewpoint_c: 21.0,
                        dewpoint_f: 69.7,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.0,
                        gust_kph: 11.2,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702846800,
                        time: '2023-12-18 04:00',
                        temp_c: 23.8,
                        temp_f: 74.9,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.8,
                        wind_kph: 6.1,
                        wind_degree: 345,
                        wind_dir: 'NNW',
                        pressure_mb: 1011.0,
                        pressure_in: 29.84,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 82,
                        cloud: 8,
                        feelslike_c: 25.9,
                        feelslike_f: 78.5,
                        windchill_c: 23.8,
                        windchill_f: 74.9,
                        heatindex_c: 25.9,
                        heatindex_f: 78.5,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.6,
                        gust_kph: 10.5,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702850400,
                        time: '2023-12-18 05:00',
                        temp_c: 23.5,
                        temp_f: 74.3,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.8,
                        wind_kph: 6.1,
                        wind_degree: 349,
                        wind_dir: 'N',
                        pressure_mb: 1011.0,
                        pressure_in: 29.85,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 83,
                        cloud: 10,
                        feelslike_c: 25.5,
                        feelslike_f: 77.9,
                        windchill_c: 23.5,
                        windchill_f: 74.3,
                        heatindex_c: 25.5,
                        heatindex_f: 77.9,
                        dewpoint_c: 20.4,
                        dewpoint_f: 68.7,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.5,
                        gust_kph: 10.5,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702854000,
                        time: '2023-12-18 06:00',
                        temp_c: 23.2,
                        temp_f: 73.7,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.8,
                        wind_kph: 6.1,
                        wind_degree: 352,
                        wind_dir: 'N',
                        pressure_mb: 1011.0,
                        pressure_in: 29.87,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 84,
                        cloud: 10,
                        feelslike_c: 25.3,
                        feelslike_f: 77.5,
                        windchill_c: 23.2,
                        windchill_f: 73.7,
                        heatindex_c: 25.3,
                        heatindex_f: 77.5,
                        dewpoint_c: 20.3,
                        dewpoint_f: 68.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 6.6,
                        gust_kph: 10.6,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702857600,
                        time: '2023-12-18 07:00',
                        temp_c: 24.1,
                        temp_f: 75.4,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.4,
                        wind_kph: 5.4,
                        wind_degree: 11,
                        wind_dir: 'NNE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.89,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 81,
                        cloud: 13,
                        feelslike_c: 26.1,
                        feelslike_f: 79.0,
                        windchill_c: 24.1,
                        windchill_f: 75.4,
                        heatindex_c: 26.1,
                        heatindex_f: 79.0,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 5.0,
                        gust_kph: 8.0,
                        uv: 6.0,
                    },
                    {
                        time_epoch: 1702861200,
                        time: '2023-12-18 08:00',
                        temp_c: 26.3,
                        temp_f: 79.3,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.1,
                        wind_kph: 5.0,
                        wind_degree: 33,
                        wind_dir: 'NNE',
                        pressure_mb: 1013.0,
                        pressure_in: 29.92,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 73,
                        cloud: 10,
                        feelslike_c: 28.4,
                        feelslike_f: 83.1,
                        windchill_c: 26.3,
                        windchill_f: 79.3,
                        heatindex_c: 28.4,
                        heatindex_f: 83.1,
                        dewpoint_c: 21.0,
                        dewpoint_f: 69.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 3.6,
                        gust_kph: 5.9,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702864800,
                        time: '2023-12-18 09:00',
                        temp_c: 28.5,
                        temp_f: 83.2,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4.0,
                        wind_degree: 47,
                        wind_dir: 'NE',
                        pressure_mb: 1013.0,
                        pressure_in: 29.92,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 64,
                        cloud: 8,
                        feelslike_c: 31.0,
                        feelslike_f: 87.8,
                        windchill_c: 28.5,
                        windchill_f: 83.2,
                        heatindex_c: 31.0,
                        heatindex_f: 87.8,
                        dewpoint_c: 21.1,
                        dewpoint_f: 69.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 2.8,
                        gust_kph: 4.6,
                        uv: 7.0,
                    },
                    {
                        time_epoch: 1702868400,
                        time: '2023-12-18 10:00',
                        temp_c: 30.6,
                        temp_f: 87.1,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 1.6,
                        wind_kph: 2.5,
                        wind_degree: 89,
                        wind_dir: 'E',
                        pressure_mb: 1013.0,
                        pressure_in: 29.91,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 57,
                        cloud: 8,
                        feelslike_c: 33.7,
                        feelslike_f: 92.6,
                        windchill_c: 30.6,
                        windchill_f: 87.1,
                        heatindex_c: 33.7,
                        heatindex_f: 92.6,
                        dewpoint_c: 21.1,
                        dewpoint_f: 69.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 1.8,
                        gust_kph: 2.9,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702872000,
                        time: '2023-12-18 11:00',
                        temp_c: 32.4,
                        temp_f: 90.4,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 2.2,
                        wind_kph: 3.6,
                        wind_degree: 105,
                        wind_dir: 'ESE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.89,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 50,
                        cloud: 9,
                        feelslike_c: 35.8,
                        feelslike_f: 96.4,
                        windchill_c: 32.4,
                        windchill_f: 90.4,
                        heatindex_c: 35.8,
                        heatindex_f: 96.4,
                        dewpoint_c: 20.8,
                        dewpoint_f: 69.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 2.6,
                        gust_kph: 4.1,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702875600,
                        time: '2023-12-18 12:00',
                        temp_c: 33.4,
                        temp_f: 92.1,
                        is_day: 1,
                        condition: {
                            text: 'Sunny',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.1,
                        wind_kph: 5.0,
                        wind_degree: 91,
                        wind_dir: 'E',
                        pressure_mb: 1011.0,
                        pressure_in: 29.85,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 46,
                        cloud: 13,
                        feelslike_c: 36.6,
                        feelslike_f: 97.9,
                        windchill_c: 33.4,
                        windchill_f: 92.1,
                        heatindex_c: 36.6,
                        heatindex_f: 97.9,
                        dewpoint_c: 20.3,
                        dewpoint_f: 68.5,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 3.6,
                        gust_kph: 5.8,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702879200,
                        time: '2023-12-18 13:00',
                        temp_c: 34.1,
                        temp_f: 93.4,
                        is_day: 1,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                            code: 1003,
                        },
                        wind_mph: 3.4,
                        wind_kph: 5.4,
                        wind_degree: 50,
                        wind_dir: 'NE',
                        pressure_mb: 1009.0,
                        pressure_in: 29.8,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 43,
                        cloud: 34,
                        feelslike_c: 37.3,
                        feelslike_f: 99.1,
                        windchill_c: 34.1,
                        windchill_f: 93.4,
                        heatindex_c: 37.3,
                        heatindex_f: 99.1,
                        dewpoint_c: 19.9,
                        dewpoint_f: 67.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 3.9,
                        gust_kph: 6.2,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702882800,
                        time: '2023-12-18 14:00',
                        temp_c: 34.5,
                        temp_f: 94.1,
                        is_day: 1,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                            code: 1003,
                        },
                        wind_mph: 3.1,
                        wind_kph: 5.0,
                        wind_degree: 34,
                        wind_dir: 'NE',
                        pressure_mb: 1008.0,
                        pressure_in: 29.77,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 41,
                        cloud: 50,
                        feelslike_c: 37.4,
                        feelslike_f: 99.4,
                        windchill_c: 34.5,
                        windchill_f: 94.1,
                        heatindex_c: 37.4,
                        heatindex_f: 99.4,
                        dewpoint_c: 19.5,
                        dewpoint_f: 67.0,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 3.6,
                        gust_kph: 5.8,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702886400,
                        time: '2023-12-18 15:00',
                        temp_c: 33.7,
                        temp_f: 92.7,
                        is_day: 1,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                            code: 1003,
                        },
                        wind_mph: 0.7,
                        wind_kph: 1.1,
                        wind_degree: 80,
                        wind_dir: 'E',
                        pressure_mb: 1008.0,
                        pressure_in: 29.76,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 44,
                        cloud: 46,
                        feelslike_c: 36.8,
                        feelslike_f: 98.2,
                        windchill_c: 33.7,
                        windchill_f: 92.7,
                        heatindex_c: 36.8,
                        heatindex_f: 98.2,
                        dewpoint_c: 19.9,
                        dewpoint_f: 67.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 0.8,
                        gust_kph: 1.3,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702890000,
                        time: '2023-12-18 16:00',
                        temp_c: 31.8,
                        temp_f: 89.3,
                        is_day: 1,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                            code: 1003,
                        },
                        wind_mph: 5.8,
                        wind_kph: 9.4,
                        wind_degree: 148,
                        wind_dir: 'SSE',
                        pressure_mb: 1008.0,
                        pressure_in: 29.77,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 51,
                        cloud: 49,
                        feelslike_c: 34.9,
                        feelslike_f: 94.7,
                        windchill_c: 31.8,
                        windchill_f: 89.3,
                        heatindex_c: 34.9,
                        heatindex_f: 94.7,
                        dewpoint_c: 20.5,
                        dewpoint_f: 68.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.3,
                        gust_kph: 13.3,
                        uv: 8.0,
                    },
                    {
                        time_epoch: 1702893600,
                        time: '2023-12-18 17:00',
                        temp_c: 29.8,
                        temp_f: 85.7,
                        is_day: 1,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                            code: 1063,
                        },
                        wind_mph: 7.6,
                        wind_kph: 12.2,
                        wind_degree: 143,
                        wind_dir: 'SE',
                        pressure_mb: 1009.0,
                        pressure_in: 29.8,
                        precip_mm: 0.01,
                        precip_in: 0.0,
                        humidity: 58,
                        cloud: 68,
                        feelslike_c: 32.4,
                        feelslike_f: 90.4,
                        windchill_c: 29.8,
                        windchill_f: 85.7,
                        heatindex_c: 32.4,
                        heatindex_f: 90.4,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.2,
                        will_it_rain: 0,
                        chance_of_rain: 45,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 12.1,
                        gust_kph: 19.5,
                        uv: 6.0,
                    },
                    {
                        time_epoch: 1702897200,
                        time: '2023-12-18 18:00',
                        temp_c: 28.7,
                        temp_f: 83.6,
                        is_day: 0,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                            code: 1063,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9.0,
                        wind_degree: 146,
                        wind_dir: 'SSE',
                        pressure_mb: 1010.0,
                        pressure_in: 29.82,
                        precip_mm: 0.08,
                        precip_in: 0.0,
                        humidity: 61,
                        cloud: 76,
                        feelslike_c: 30.9,
                        feelslike_f: 87.5,
                        windchill_c: 28.7,
                        windchill_f: 83.6,
                        heatindex_c: 30.9,
                        heatindex_f: 87.5,
                        dewpoint_c: 20.3,
                        dewpoint_f: 68.5,
                        will_it_rain: 0,
                        chance_of_rain: 45,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.1,
                        gust_kph: 14.6,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702900800,
                        time: '2023-12-18 19:00',
                        temp_c: 27.9,
                        temp_f: 82.3,
                        is_day: 0,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                            code: 1063,
                        },
                        wind_mph: 4.7,
                        wind_kph: 7.6,
                        wind_degree: 157,
                        wind_dir: 'SSE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.85,
                        precip_mm: 0.12,
                        precip_in: 0.0,
                        humidity: 63,
                        cloud: 89,
                        feelslike_c: 30.0,
                        feelslike_f: 86.0,
                        windchill_c: 28.0,
                        windchill_f: 82.3,
                        heatindex_c: 30.0,
                        heatindex_f: 86.0,
                        dewpoint_c: 20.3,
                        dewpoint_f: 68.5,
                        will_it_rain: 1,
                        chance_of_rain: 100,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 7.8,
                        gust_kph: 12.5,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702904400,
                        time: '2023-12-18 20:00',
                        temp_c: 27.1,
                        temp_f: 80.8,
                        is_day: 0,
                        condition: {
                            text: 'Patchy rain possible',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                            code: 1063,
                        },
                        wind_mph: 4.9,
                        wind_kph: 7.9,
                        wind_degree: 162,
                        wind_dir: 'SSE',
                        pressure_mb: 1011.0,
                        pressure_in: 29.87,
                        precip_mm: 0.01,
                        precip_in: 0.0,
                        humidity: 67,
                        cloud: 70,
                        feelslike_c: 29.1,
                        feelslike_f: 84.4,
                        windchill_c: 27.1,
                        windchill_f: 80.8,
                        heatindex_c: 29.1,
                        heatindex_f: 84.4,
                        dewpoint_c: 20.5,
                        dewpoint_f: 68.8,
                        will_it_rain: 0,
                        chance_of_rain: 45,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 8.4,
                        gust_kph: 13.5,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702908000,
                        time: '2023-12-18 21:00',
                        temp_c: 26.5,
                        temp_f: 79.6,
                        is_day: 0,
                        condition: {
                            text: 'Partly cloudy',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                            code: 1003,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9.0,
                        wind_degree: 164,
                        wind_dir: 'SSE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.88,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 71,
                        cloud: 26,
                        feelslike_c: 28.5,
                        feelslike_f: 83.2,
                        windchill_c: 26.5,
                        windchill_f: 79.6,
                        heatindex_c: 28.5,
                        heatindex_f: 83.2,
                        dewpoint_c: 20.7,
                        dewpoint_f: 69.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.7,
                        gust_kph: 15.6,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702911600,
                        time: '2023-12-18 22:00',
                        temp_c: 25.7,
                        temp_f: 78.3,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 5.1,
                        wind_kph: 8.3,
                        wind_degree: 156,
                        wind_dir: 'SSE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.88,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 75,
                        cloud: 24,
                        feelslike_c: 27.8,
                        feelslike_f: 82.0,
                        windchill_c: 25.8,
                        windchill_f: 78.4,
                        heatindex_c: 27.8,
                        heatindex_f: 82.0,
                        dewpoint_c: 21.0,
                        dewpoint_f: 69.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 9.1,
                        gust_kph: 14.7,
                        uv: 1.0,
                    },
                    {
                        time_epoch: 1702915200,
                        time: '2023-12-18 23:00',
                        temp_c: 25.7,
                        temp_f: 78.2,
                        is_day: 0,
                        condition: {
                            text: 'Clear',
                            icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                            code: 1000,
                        },
                        wind_mph: 3.4,
                        wind_kph: 5.4,
                        wind_degree: 155,
                        wind_dir: 'SSE',
                        pressure_mb: 1012.0,
                        pressure_in: 29.87,
                        precip_mm: 0.0,
                        precip_in: 0.0,
                        humidity: 77,
                        cloud: 18,
                        feelslike_c: 27.8,
                        feelslike_f: 82.0,
                        windchill_c: 25.7,
                        windchill_f: 78.2,
                        heatindex_c: 27.8,
                        heatindex_f: 82.0,
                        dewpoint_c: 21.3,
                        dewpoint_f: 70.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10.0,
                        vis_miles: 6.0,
                        gust_mph: 5.9,
                        gust_kph: 9.5,
                        uv: 1.0,
                    },
                ],
            },
        ],
    },
}
