export const WEATHER_ICON = {
    'Partly cloudy': require('@assets/images/partlycloudy.png'),
    'Moderate rain': require('@assets/images/moderaterain.png'),
    'Patchy rain possible': require('@assets/images/moderaterain.png'),
    'Patchy light rain': require('@assets/images/moderaterain.png'),
    Sunny: require('@assets/images/sun.png'),
    Clear: require('@assets/images/sun.png'),
    Overcast: require('@assets/images/cloud.png'),
    Cloudy: require('@assets/images/cloud.png'),
    'Light rain': require('@assets/images/moderaterain.png'),
    'Moderate rain at times': require('@assets/images/moderaterain.png'),
    'Heavy rain': require('@assets/images/heavyrain.png'),
    'Heavy rain at times': require('@assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('@assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('@assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('@assets/images/heavyrain.png'),
    Mist: require('@assets/images/mist.png'),
    other: require('@assets/images/moderaterain.png'),
}

export const WEATHER_NAME = {
    'Partly cloudy': 'Nhiều mây',
    'Moderate rain': 'Mưa vừa',
    'Patchy rain possible': 'Mưa rải rác',
    'Patchy light rain': 'Mưa rải rác',
    Sunny: 'Nắng',
    Clear: 'Trời quang đãng',
    Overcast: 'Trời âm u',
    Cloudy: 'Nhiều mây',
    'Light rain': 'Mưa nhỏ',
    'Light rain shower': 'Mưa nhỏ',
    'Moderate rain at times': 'Có lúc mưa vừa',
    'Heavy rain': 'Mưa to',
    'Heavy rain at times': 'Có lúc mưa to',
    'Moderate or heavy freezing rain': 'Mưa lạnh',
    'Moderate or heavy rain shower': 'Mưa vừa',
    'Moderate or heavy rain with thunder': 'Mưa có sấm',
    Mist: 'Sương mù',
    other: 'Khác',
}

export const WIND_DIRECTION = {
    N: 'Bắc',
    NNE: 'Bắc Đông Bắc',
    NE: 'Đông Bắc',
    ENE: 'Đông Đông Bắc',
    E: 'Đông',
    ESE: 'Đông Đông Nam',
    SE: 'Đông Nam',
    SSE: 'Nam Đông Nam',
    S: 'Nam',
    SSW: 'Nam Tây Nam',
    SW: 'Tây Nam',
    WSW: 'Tây Tây Nam',
    W: 'Tây',
    WNW: 'Tây Tây Bắc',
    NW: 'Tây Bắc',
    NNW: 'Bắc Tây Bắc',
}
