export const weatherImages = {
    'Partly cloudy': require('../../assets/images/partlycloudy.png'),
    'Moderate rain': require('../../assets/images/moderaterain.png'),
    'Patchy rain possible': require('../../assets/images/moderaterain.png'),
    'Sunny': require('../../assets/images/sun.png'),
    'Clear': require('../../assets/images/sun.png'),
    'Overcast': require('../../assets/images/cloud.png'),
    'Cloudy': require('../../assets/images/cloud.png'),
    'Light rain': require('../../assets/images/moderaterain.png'),
    'Moderate rain at times': require('../../assets/images/moderaterain.png'),
    'Heavy rain': require('../../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../../assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('../../assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('../../assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('../../assets/images/heavyrain.png'),
    'Mist': require('../../assets/images/mist.png'),
    'other': require('../../assets/images/moderaterain.png')
}
export const weatherBackgroundImages = {
    'Partly cloudy': require('../../assets/backgrounds/screen/sunny.jpg'),
    'Moderate rain': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Patchy rain possible': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Sunny': require('../../assets/backgrounds/screen/sunny.jpg'),
    'Clear': require('../../assets/backgrounds/screen/sunny.jpg'),
    'Overcast': require('../../assets/backgrounds/screen/cloudy.jpg'),
    'Cloudy': require('../../assets/backgrounds/screen/cloudy.jpg'),
    'Light rain': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Moderate rain at times': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Heavy rain': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Heavy rain at times': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Moderate or heavy freezing rain': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Moderate or heavy rain shower': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Moderate or heavy rain with thunder': require('../../assets/backgrounds/screen/rainy.jpg'),
    'Mist': require('../../assets/backgrounds/screen/cloudy.jpg'),
    'other': require('../../assets/backgrounds/screen/cloudy.jpg')
}
export const citiItemImages = {
    'Partly cloudy': require('../../assets/backgrounds/citiItem/sunny.jpg'),
    'Moderate rain': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Patchy rain possible': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Sunny': require('../../assets/backgrounds/citiItem/sunny.jpg'),
    'Clear': require('../../assets/backgrounds/citiItem/sunny.jpg'),
    'Overcast': require('../../assets/backgrounds/citiItem/cloudy.jpg'),
    'Cloudy': require('../../assets/backgrounds/citiItem/cloudy.jpg'),
    'Light rain': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Moderate rain at times': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Heavy rain': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Heavy rain at times': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Moderate or heavy freezing rain': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Moderate or heavy rain shower': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Moderate or heavy rain with thunder': require('../../assets/backgrounds/citiItem/rainy.jpg'),
    'Mist': require('../../assets/backgrounds/citiItem/cloudy.jpg'),
    'other': require('../../assets/backgrounds/citiItem/cloudy.jpg')
}
